### ISSUE TITLE
Lua Error SlotButtons

### ISSUE THREAD

**Issue by dspearing** [Haleth/Aurora#281] opened 2021-07-26 05:36 UTC
32x ...eAurora\SkinBlizzard_Collections-1.0.lua:821: attempt to get length of field 'SlotButtons' (a nil value)
[string "@Aurora\SkinBlizzard_Collections-1.0.lua"]:821: in function `addonModule'
[string "@Aurora\Skin\init.lua"]:248: in function <Aurora\Skin\init.lua:212>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:508: in function `UIParentLoadAddOn'
[string "@Rarity\Core\Collections-Collections.lua"]:63: in function `ScanToys'
[string "@Rarity\Core\Collections-Collections.lua"]:307: in function `ScanExistingItems'
[string "@Rarity\Core.lua"]:175: in function `DoEnable'
[string "@Rarity\Core.lua"]:151: in function <Rarity\Core.lua:150>
[string "=[C]"]: ?
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals:
CollectionsJournal = CollectionsJournal {
 0 = <userdata>
 TitleText = CollectionsJournalTitleText {
 }
 portrait = CollectionsJournalPortrait {
 }
 SetBorder = <function> defined =[C]:-1
 layoutType = "PortraitFrameTemplate"
 SetPortraitShown = <function> defined @SharedXML\PortraitFrame.lua:52
 SetPortraitAtlasRaw = <function> defined @SharedXML\PortraitFrame.lua:44
 SetPortraitToUnit = <function> defined @SharedXML\PortraitFrame.lua:36
 SetPortraitTexCoord = <function> defined @SharedXML\PortraitFrame.lua:48
 SetPortraitTextureRaw = <function> defined @SharedXML\PortraitFrame.lua:40
 SetTitleFormatted = <function> defined @SharedXML\PortraitFrame.lua:64
 NineSlice = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 TitleBg = <unnamed> {
 }
 SetPortraitToAsset = <function> defined @SharedXML\PortraitFrame.lua:32
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML\PortraitFrame.lua:68
 SetTitleColor = <function> defined @SharedXML\PortraitFrame.lua:56
 CloseButton = CollectionsJournalCloseButton {
 }
 selectedTab = 5
 numTabs = 5
 SetTitle = <function> defined @SharedXML\PortraitFrame.lua:60
 Bg = CollectionsJournalBg {
 }
}
MountJournal = MountJournal {
 0 = <userdata>
 MountDisplay = <unnamed> {
 }
 BackgroundOverlay = <unnamed> {
 }
 SummonRandomFavoriteButton = MountJournalSummonRandomFavoriteButton {
 }
 SlotButton = <unnamed> {
 }
 RightInset = <unnamed> {
 }
 ListScrollFrame = MountJournalListScrollFrame {
 }
 MountButton = MountJournalMountButton {
 }
 SuppressedMountEquipmentButton = <unnamed> {
 }
 MountCount = <unnamed> {
 }
 BottomLeftInset = <unnamed> {
 }
 mountOptionsMenu = MountJournalMountOptionsMenu {
 }
 LeftInset = <unnamed> {
 }
 searchBox = MountJournalSearchBox {
 }
 SlotRequirementLabel = <unnamed> {
 }
 SlotLabel = <unnamed> {
 }
}
BottomLeftInset = <unnamed> {
 0 = <userdata>
 SlotRequirementLabel = <unnamed> {
 }
 SuppressedMountEquipmentButton = <unnamed> {
 }
 layoutType = "InsetFrameTemplate"
 SlotButton = <unnamed> {
 }
 BackgroundOverlay = <unnamed> {
 }
 SlotLabel = <unnamed> {
 }
 Background = <unnamed> {
 }
 Bg = <unnamed> {
 }
 NineSlice = <unnamed> {
 }
}
MountDisplay = <unnamed> {
 0 = <userdata>
 InfoButton = <unnamed> {
 }
 YesMountsTex = <unnamed> {
 }
 ShadowOverlay = <unnamed> {
 }
 NoMounts = <unnamed> {
 }
 NoMountsTex = <unnamed> {
 }
 ModelScene = <unnamed> {
 }
}
PetJournal = PetJournal {
 0 = <userdata>
 LeftInset = PetJournalLeftInset {
 }
 searchBox = PetJournalSearchBox {
 }
 loadoutBorder = PetJournalLoadoutBorder {
 }
 listScroll = PetJournalListScrollFrame {
 }
 SpellSelect = PetJournalSpellSelect {
 }
 RightInset = PetJournalRightInset {
 }
 SummonButton = PetJournalSummonButton {
 }
 PetCard = PetJournalPetCard {
 }
 AchievementStatus = PetJournalAchievementStatus {
 }
 PetCount = <unnamed> {
 }
 Loadout = PetJournalLoadout {
 }
 SummonRandomFavoritePetButton = PetJournalSummonRandomFavoritePetButton {
 }
 MainHelpButton = PetJournalTutorialButton {
 }
 petOptionsMenu = PetJournalPetOptionsMenu {
 }
 PetCardInset = PetJournalPetCardInset {
 }
 HealPetButton = PetJournalHealPetButton {
 }
 FindBattleButton = PetJournalFindBattle {
 }
}
PetCard = PetJournalPetCard {
 0 = <userdata>
 CannotBattleText = <unnamed> {
 }
 SpeedFrame = PetJournalPetCardSpeedFrame {
 }
 PetInfo = PetJournalPetCardPetInfo {
 }
 AbilitiesBG3 = PetJournalPetCardAbilitiesBG3 {
 }
 AbilitiesBG1 = PetJournalPetCardAbilitiesBG1 {
 }
 AbilitiesBG2 = PetJournalPetCardAbilitiesBG2 {
 }
 spell6 = PetJournalPetCardSpell6 {
 }
 petIndex = 1
 spell5 = PetJournalPetCardSpell5 {
 }
 shadows = PetJournalPetCardShadows {
 }
 displayID = 78244
 speciesID = 2403
 PowerFrame = PetJournalPetCardPowerFrame {
 }
 HealthFrame = PetJournalPetCardHealthFrame {
 }
 QualityFrame = PetJournalPetCardQualityFrame {
 }
 spell1 = PetJournalPetCardSpell1 {
 }
 xpBar = PetJournalPetCardXPBar {
 }
 spell4 = PetJournalPetCardSpell4 {
 }
 spell3 = PetJournalPetCardSpell3 {
 }
 modelScene = <unnamed> {
 }
 spell2 = PetJourn

**Comment by Gethe** [comment] 2021-08-24 20:31
Duplicate of #275

**Closed as completed by Gethe** 2021-08-24 20:31 UTC
Labels: bug
