### ISSUE TITLE
Wow hangs when clicking aurora on interface>addons

### ISSUE THREAD

**Issue by johnnydement** [Haleth/Aurora#195] opened 2020-04-17 11:28 UTC
### Description ###

When I click aurora options in interface>addons wow hangs

### Steps to Reproduce ###

1. Click ESC
2. Click interface
3. Click addons
4. Click Aurora

**Expected behavior:**

Aurora options opens

**Actual behavior:**

Wow hangs

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [No]

I'm a new aurora user, just installed it for the first time

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

It happens everytime I try to enter it's options, I'm still on the first step on configuring the new UI

**Screenshots and GIFs**

https://youtu.be/3Rl-cvt-e-I

![image](https://user-images.githubusercontent.com/1867306/79563206-9e7ddb80-80ac-11ea-9c43-120f9917173f.png)

**Installed AddOns:**

!KalielsTracker
ACP
AdvancedInterfaceOptions
ArkInventory
ArkInventoryConfig
ArkInventoryRules
ArkInventoryRules_Example
ArkInventoryRules_MoreRules
ArkInventorySearch
Aurora
Aurora_Extension
AzeriteTooltip
AzeriteUI
Bartender4
Bartender4Arched
BasicMinimap
BasicMinimap_Options
BetterBattlePetTooltip
BtWQuests
BtWQuestsBattleForAzeroth
BuyEmAll
ConvertRatings
CursorTrail
DBM-AntorusBurningThrone
DBM-AQ20
DBM-AQ40
DBM-Argus
DBM-Azeroth
DBM-Azeroth-BfA
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackrockFoundry
DBM-BlackTemple
DBM-BlackwingDescent
DBM-Brawlers
DBM-BrokenIsles
DBM-BWL
DBM-Challenges
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-CrucibleofStorms
DBM-DefaultSkin
DBM-DMF
DBM-Draenor
DBM-DragonSoul
DBM-EmeraldNightmare
DBM-EternalPalace
DBM-EyeOfEternity
DBM-Firelands
DBM-GarrisonInvasions
DBM-GUI
DBM-HeartofFear
DBM-HellfireCitadel
DBM-Highmaul
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-MC
DBM-MogushanVaults
DBM-Naxx
DBM-Nighthold
DBM-Nyalotha
DBM-Onyxia
DBM-Outlands
DBM-Pandaria
DBM-Party-BC
DBM-Party-BfA
DBM-Party-Cataclysm
DBM-Party-Classic
DBM-Party-Legion
DBM-Party-MoP
DBM-Party-WoD
DBM-Party-WotLK
DBM-PvP
DBM-Scenario-MoP
DBM-Serpentshrine
DBM-SiegeOfOrgrimmarV2
DBM-StatusBarTimers
DBM-Sunwell
DBM-TerraceofEndlessSpring
DBM-TheEye
DBM-ThroneFourWinds
DBM-ThroneofThunder
DBM-TombofSargeras
DBM-TrialofValor
DBM-Uldir
DBM-Ulduar
DBM-VoA
DBM-WorldEvents
DBM-ZuldazarRaid
Details
Details_DataStorage
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
df-ArkInventoryRules
DynamicCam
eAlignUpdated
Experiencer
FasterLoot
FishingBuddy
GarrisonMissionManager
GatherMate2
GatherMate2_Data
GTFO
HandyNotes
HandyNotes_Argus
HandyNotes_BattleForAzerothTreasures
HandyNotes_BrokenShore
HandyNotes_CamelFigurines
HandyNotes_DraenorTreasures
HandyNotes_HigherDimensionalLearning
HandyNotes_Kosumoth
HandyNotes_LegionClassOrderHalls
HandyNotes_LegionRaresTreasures
HandyNotes_LongForgottenHippogryph
HandyNotes_LostAndFound
HandyNotes_MechagonAndNazjatar
Handynotes_Pandaria
HandyNotes_SuramarLeylines
HandyNotes_SuramarTelemancy
HandyNotes_TimelessIsle_RareElites
HandyNotes_TimelessTreasures
HandyNotes_TravelGuide
HandyNotes_VisionsOfNZoth
HandyNotes_WarfrontRares
Healium
Immersion
Immersive
Kong
KongConfig
Kui_Media
Kui_Nameplates
Kui_Nameplates_Core
Kui_Nameplates_Core_Config
Kui_Nameplates_Elite
Kui_Nameplates_Spell_Alert
LibPetJournal-2.0
MacroToolkit
MacroToolkitIcons
Masque
Masque_Azerite
 Masque_Cirque
Masque_CleanUI
MinimapButtonFrame
MinimapButtonFrame_SkinPack
MogIt
MogIt_Artifact
MogIt_Cloth
MogIt_Highlighter
MogIt_Leather
MogIt_Mail
MogIt_OneHanded
MogIt_Other
MogIt_Plate
MogIt_Ranged
MogIt_SetTransmog
MogIt_TwoHanded
Molinari
mOnArs_WardrobeHelper
MountJournalEnhanced
MoveAnything
NomiCakes
OPie
OPieMasque
Overachiever
 Overachiever_Cache
Overachiever_Tabs
Overachiever_Trade
ParagonReputation
Pawn
PetJournalEnhanced
PetTracker
PetTracker_Battle
PetTracker_Config
PetTracker_Journal
PhanxBuffs
Postal
Prat-3.0
Prat-3.0_Libraries
PreciseWorldQuestTimers
Profession_Assistance
RaiderIO
RaiderIO_DB_EU_A
 RaiderIO_DB_EU_A_R
RaiderIO_DB_EU_H
RaiderIO_DB_EU_H_R
RaiderIO_DB_KR_A
RaiderIO_DB_KR_A_R
RaiderIO_DB_KR_H
RaiderIO_DB_KR_H_R
RaiderIO_DB_TW_A
RaiderIO_DB_TW_A_R
RaiderIO_DB_TW_H
RaiderIO_DB_TW_H_R
RaiderIO_DB_US_A
RaiderIO_DB_US_A_R
RaiderIO_DB_US_H
RaiderIO_DB_US_H_R
RareScanner
Rematch
RepHelper
SilverDragon
SilverDragon_BattleForAzeroth
SilverDragon_BurningCrusade
SilverDragon_Cataclysm
SilverDragon_Legion
SilverDragon_Mists
SilverDragon_Vanilla
SilverDragon_Warlords
SilverDragon_Wrath
Simulationcraft
Skillet
TabardAddict
TomPoints
TomTom
totalRP3
totalRP3_Data
totalRP3_KuiNameplates
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
WorldMapTrackingEnhanced
WorldQuestsList

**Comment by Gethe** [comment] 2020-04-17 13:39
I'm not able to reproduce this issue, it's likely a conflict with another addon.

**Comment by Gethe** [comment] 2020-07-01 01:58
Closing due to lack of further comment

**Closed by Gethe** 2020-07-01 01:58 UTC
