### ISSUE TITLE
[Bug] backdrop.lua:585: attempt to index local 'frame' (a nil value)

### ISSUE THREAD

**Issue by CrisReus** [Haleth/Aurora#244] opened 2020-11-18 12:19 UTC
3x Aurora\Skin\backdrop.lua:585: attempt to index local 'frame' (a nil value)
[string "@Aurora\Skin\backdrop.lua"]:585: in function `SetBackdrop'
[string "@Aurora\SkinBlizzard_EncounterJournal-1.0.lua"]:136: in function `EJButtonTemplate'
[string "@Aurora\SkinBlizzard_EncounterJournal-1.0.lua"]:569: in function `addonModule'
[string "@Aurora\Skin\init.lua"]:246: in function <Aurora\Skin\init.lua:210>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:661: in function `EncounterJournal_LoadUI'
[string "@FrameXML\UIParent.lua"]:1045: in function `ToggleEncounterJournal'
[string "@FrameXML\MainMenuBarMicroButtons.lua"]:1209: in function <FrameXML\MainMenuBarMicroButtons.lua:1207>
[string "=[C]"]: ?

Locals:
frame = nil
color = <table> {
 colorStr = "ff666666"
 b = 0.400000
 Lightness = <function> defined @Aurora\Skin\color.lua:71
 g = 0.400000
 GetRGBA = <function> defined @SharedXML\Color.lua:28
 Saturation = <function> defined @Aurora\Skin\color.lua:65
 SetRGB = <function> defined @SharedXML\Color.lua:43
 Hue = <function> defined @Aurora\Skin\color.lua:59
 GetRGB = <function> defined @SharedXML\Color.lua:20
 r = 0.400000
 GenerateHexColorMarkup = <function> defined @SharedXML\Color.lua:51
 WrapTextInColorCode = <function> defined @SharedXML\Color.lua:55
 GenerateHexColor = <function> defined @SharedXML\Color.lua:47
 IsEqualTo = <function> defined @Aurora\Skin\color.lua:42
 isAchromatic = true
 SetRGBA = <function> defined @Aurora\Skin\color.lua:29
 OnLoad = <function> defined @SharedXML\Color.lua:9
 GetRGBAsBytes = <function> defined @SharedXML\Color.lua:24
 GetRGBAAsBytes = <function> defined @SharedXML\Color.lua:32
}
alpha = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"
Base = <table> {
 SetHighlight = <function> defined @Aurora\Skin\deprecated.lua:13
 SetTexture = <function> defined @Aurora\Skin\api.lua:214
 SetFont = <function> defined @Aurora\Skin\api.lua:90
 IsTextureRegistered = <function> defined @Aurora\Skin\api.lua:210
 SetBackdropColor = <function> defined @Aurora\Skin\backdrop.lua:591
 SetBackdrop = <function> defined @Aurora\Skin\backdrop.lua:584
 CropIcon = <function> defined @Aurora\Skin\api.lua:78
 GetAddonSkins = <function> defined @Aurora\Skin\api.lua:55
 AddSkin = <function> defined @Aurora\Skin\api.lua:39
 CreateBackdrop = <function> defined @Aurora\Skin\backdrop.lua:565
 RegisterTexture = <function> defined @Aurora\Skin\api.lua:224
}
backdrop = <table> {
 bgFile = "Buttons\WHITE8x8"
 tile = true
 backdropBorderSubLevel = -7
 offsets = <table> {
 }
 backdropSubLevel = -8
 edgeFile = "Buttons\WHITE8x8"
 backdropBorderLayer = "BACKGROUND"
 backdropLayer = "BACKGROUND"
 edgeSize = 1
 insets = <table> {
 }
}

**Comment by Gethe** [comment] 2020-11-18 16:19
Duplicate of #242

**Closed by Gethe** 2020-11-18 16:19 UTC
Labels: bug
