### ISSUE TITLE
Shop Preview

### ISSUE THREAD

**Issue by Anothersignup** [Haleth/Aurora#143] opened 2018-11-03 06:43 UTC
Message: Interface\AddOns\Aurora\Skin\api.lua:383: attempt to call field '_auroraSetColor' (a nil value)
Time: Sat Nov  3 07:39:35 2018
Count: 8
Stack: Interface\AddOns\Aurora\Skin\api.lua:383: attempt to call field '_auroraSetColor' (a nil value)
Interface\AddOns\Aurora\Skin\api.lua:383: in function <Interface\AddOns\Aurora\Skin\api.lua:376>
Interface\AddOns\Aurora\Skin\api.lua:413: in function <Interface\AddOns\Aurora\Skin\api.lua:412>
[C]: ?
[C]: ?

Locals: button = ModelPreviewFrameCloseButton {
 0 = <userdata>
 _returnColor = <table> {
 }
 _auroraHighlight = <table> {
 }
 Right = <unnamed> {
 }
 Left = <unnamed> {
 }
 GetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:239
 SetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:245
 Middle = <unnamed> {
 }
 SetBackdropBorderLayer = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:275
 GetBackdropTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:295
 GetBackdropBorderLayer = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:290
 Text = ModelPreviewFrameCloseButtonText {
 }
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:91
 GetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:269
 GetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:209
 LeftSeparator = ModelPreviewFrameCloseButton_LeftSeparator {
 }
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:221
 _auroraBackdrop = <table> {
 }
}
isBackground = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <unnamed> {
 }
}
(for control) = 1
_ = 1
texture = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0.96
(*temporary) = 0.55
(*temporary) = 0.73
(*temporary) = "attempt to call field '_auroraSetColor' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:875
 grayLight = <table> {
 }
 Saturation = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:871
 button = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:867
 blue = <table> {
 }
 Post = <table> {
 }
 Create = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:891
 white = <table> {
 }
 frame = <table> {
 }
 grayDark = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 violet = <table> {
 }
 gray = <table> {
 }
}
Base = <table> {
 SetHighlight = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:397
 GetSkinList = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:41
 SetTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:530
 CreateBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:301
 SetBackdrop = <function> defined =[C]:-1
 CreateColor = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:891
 Post = <table> {
 }
 IsTextureRegistered = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:526
 RegisterTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:548
 CropIcon = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:55
 Pre = <table> {
 }
 AddSkin = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:33
 SetFont = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:329
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\deprecated.lua:38
}

**Comment by Gethe** [comment] 2018-11-07 00:36
Duplicate of #142

**Closed by Gethe** 2018-11-07 00:36 UTC
