### ISSUE TITLE
[Bug] Opening PVP Tab

### ISSUE THREAD

**Issue by Epidemdabear** [Haleth/Aurora#250] opened 2020-12-02 17:36 UTC
When selecting the Player vs Player tab in Group Finder get the following error :

3x Aurora\SkinBlizzard_PVPUI-1.0.lua:217: attempt to call method 'SetTextColor' (a nil value)
[string "@Aurora\SkinBlizzard_PVPUI-1.0.lua"]:217: in function `addonModule'
[string "@Aurora\Skin\init.lua"]:246: in function <Aurora\Skin\init.lua:210>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\PVEFrame.lua"]:120: in function `PVEFrame_ShowFrame'
[string "@FrameXML\PVEFrame.lua"]:88: in function `PVEFrame_ToggleFrame'
[string "@FrameXML\UIParent.lua"]:1116: in function `TogglePVPUI'
[string "TOGGLECHARACTER4"]:1: in function <[string "TOGGLECHARACTER4"]:1>

Locals:
PVPQueueFrame = PVPQueueFrame {
 0 = <userdata>
 HonorInset = <unnamed> {
 }
 CategoryButton2 = PVPQueueFrameCategoryButton2 {
 }
 CategoryButton3 = PVPQueueFrameCategoryButton3 {
 }
 update = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:394
 selection = HonorFrame {
 }
 PrestigeLevelDialog = PVPTalentPrestigeLevelDialog {
 }
 CategoryButton1 = PVPQueueFrameCategoryButton1 {
 }
 getSelection = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:390
 NewSeasonPopup = <unnamed> {
 }
 PrestigePortrait = <unnamed> {
 }
}
HonorFrame = HonorFrame {
 0 = <userdata>
 TankIcon = <unnamed> {
 }
 QueueButton = HonorFrameQueueButton {
 }
 ConquestBar = <unnamed> {
 }
 BonusFrame = <unnamed> {
 }
 type = "bonus"
 SpecificFrame = HonorFrameSpecificFrame {
 }
 HealerIcon = <unnamed> {
 }
 Inset = <unnamed> {
 }
 DPSIcon = <unnamed> {
 }
}
BonusFrame = <unnamed> {
 0 = <userdata>
 ShadowOverlay = <unnamed> {
 }
 Arena1Button = <unnamed> {
 }
 WorldBattlesTexture = <unnamed> {
 }
 BrawlButton = <unnamed> {
 }
 RandomBGButton = <unnamed> {
 }
 SpecialEventButton = <unnamed> {
 }
 RandomEpicBGButton = <unnamed> {
 }
}
ConquestFrame = ConquestFrame {
 Arena2v2 = <unnamed> {
 }
 TankIcon = <unnamed> {
 }
 RatedBG = <unnamed> {
 }
 ShadowOverlay = <unnamed> {
 }
 Arena3v3 = <unnamed> {
 }
 JoinButton = ConquestJoinButton {
 }
 ConquestBar = <unnamed> {
 }
 ArenaInviteMenu = ConquestFrameArenaInviteMenu {
 }
 Disabled = <unnamed> {
 }
 NoSeason = <unnamed> {
 }
 HealerIcon = <unnamed> {
 }
 seasonState = 1
 0 = <userdata>
 RatedBGTexture = <unnamed> {
 }
 Inset = <unnamed> {
 }
 DPSIcon = <unnamed> {
 }
}
HonorInset = <unnamed> {
 0 = <userdata>
 DisplayRatedPanel = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:1659
 NineSlice = <unnamed> {
 }
 Update = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:1589
 RatedPanel = <unnamed> {
 }
 CasualPanel = <unnamed> {
 }
 DisplayCasualPanel = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:1605
 Bg = <unnamed> {
 }
 layoutType = "InsetFrameTemplate"
}
_ = <unnamed> {
 0 = <userdata>
}
bg2 = <unnamed> {
 0 = <userdata>
}
CasualPanel = <unnamed> {
 0 = <userdata>
 LegacyOnShow = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:2194
 OnShow = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:2207
 HKLabel = <unnamed> {
 }
 HonorLevelDisplay = <unnamed> {
 }
 WeeklyChest = <unnamed> {
 }
 HKValue = <unnamed> {
 }
}
NextRewardLevel = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML\PVPUITemplates.lua:150
 Update = <function> defined @FrameXML\PVPUITemplates.lua:168
 CircleMask = <unnamed> {
 }
 LevelLabel = <unnamed> {
 }
 OnLeave = <function> defined @FrameXML\PVPUITemplates.lua:165
 RingBorder = <unnamed> {
 }
 RewardIcon = <unnamed> {
 }
 IconCover = <unnamed> {
 }
}
RatedPanel = <unnamed> {
 0 = <userdata>
 LegacyOnShow = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:2232
 OnShow = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:2236
 Label = <unnamed> {
 }
 SeasonRewardFrame = <unnamed> {
 }
 WeeklyChest = <unnamed> {
 }
 Tier = <unnamed> {
 }
}
NewSeasonPopup = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 RightBorder = <unnamed> {
 }
 LeftBorder = <unnamed> {
 }
 LeftHide = <unnamed> {
 }
 RightHide2 = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightHide = <unnamed> {
 }
 SeasonRewardFrame = <unnamed> {
 }
 SeasonRewardText = <unnamed> {
 }
 TopBorder = <unnamed> {
 }
 OnShow = <function> defined @Blizzard_PVPUI\Blizzard_PVPUI.lua:2018
 Leave = <unnamed> {
 }
 SeasonDescription2 = <unnamed> {
 }
 BottomBorder = <unnamed> {
 }
 SeasonDescription = <unnamed> {
 }
 NewSeason = <unnamed> {
 }
 LeftHide2 = <unnamed> {
 }
 BottomHide2 = <unnamed> {
 }
 TopLeftFiligree = <unnamed> {
 }
 Background = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 0 = <userdata>
 TopRightFiligree = <unnamed> {

**Comment by Gethe** [comment] 2020-12-02 23:46
Duplicate of #248

**Closed by Gethe** 2020-12-02 23:46 UTC
Labels: bug
